name: metagenome-benchmark
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # Python and core packages
  - python=3.11
  - uv  # Fast Python package installer
  
  # Bioinformatics tools (conda-only packages)
  - nextflow
  - singularity
  - checkm-genome
  - busco
  - gtdbtk
  - eggnog-mapper
  - amber-eval
  
  # System dependencies that work better with conda
  - git
  - curl
  - wget
  
  # Additional tools via uv (in requirements.txt)
  # Most Python packages will be installed via uv for speed